runtime: nodejs10
service: wellnecity-staging
env: standard
instance_class: F2
handlers:
  - url: /(.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js))$
    static_files: dist/\1
    upload: dist/(.*)
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html